# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import watchlists_pb2 as watchlists__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in watchlists_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WatchlistServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListWatchlists = channel.unary_unary(
                '/movieplatform.watchlists.v1.WatchlistService/ListWatchlists',
                request_serializer=watchlists__pb2.ListWatchlistsRequest.SerializeToString,
                response_deserializer=watchlists__pb2.ListWatchlistsResponse.FromString,
                _registered_method=True)
        self.GetWatchlist = channel.unary_unary(
                '/movieplatform.watchlists.v1.WatchlistService/GetWatchlist',
                request_serializer=watchlists__pb2.GetWatchlistRequest.SerializeToString,
                response_deserializer=watchlists__pb2.GetWatchlistResponse.FromString,
                _registered_method=True)
        self.CreateWatchlist = channel.unary_unary(
                '/movieplatform.watchlists.v1.WatchlistService/CreateWatchlist',
                request_serializer=watchlists__pb2.CreateWatchlistRequest.SerializeToString,
                response_deserializer=watchlists__pb2.CreateWatchlistResponse.FromString,
                _registered_method=True)
        self.UpdateWatchlist = channel.unary_unary(
                '/movieplatform.watchlists.v1.WatchlistService/UpdateWatchlist',
                request_serializer=watchlists__pb2.UpdateWatchlistRequest.SerializeToString,
                response_deserializer=watchlists__pb2.UpdateWatchlistResponse.FromString,
                _registered_method=True)
        self.DeleteWatchlist = channel.unary_unary(
                '/movieplatform.watchlists.v1.WatchlistService/DeleteWatchlist',
                request_serializer=watchlists__pb2.DeleteWatchlistRequest.SerializeToString,
                response_deserializer=watchlists__pb2.DeleteWatchlistResponse.FromString,
                _registered_method=True)
        self.GetUserWatchlists = channel.unary_unary(
                '/movieplatform.watchlists.v1.WatchlistService/GetUserWatchlists',
                request_serializer=watchlists__pb2.GetUserWatchlistsRequest.SerializeToString,
                response_deserializer=watchlists__pb2.GetUserWatchlistsResponse.FromString,
                _registered_method=True)
        self.AddMovieToWatchlist = channel.unary_unary(
                '/movieplatform.watchlists.v1.WatchlistService/AddMovieToWatchlist',
                request_serializer=watchlists__pb2.AddMovieToWatchlistRequest.SerializeToString,
                response_deserializer=watchlists__pb2.AddMovieToWatchlistResponse.FromString,
                _registered_method=True)
        self.RemoveMovieFromWatchlist = channel.unary_unary(
                '/movieplatform.watchlists.v1.WatchlistService/RemoveMovieFromWatchlist',
                request_serializer=watchlists__pb2.RemoveMovieFromWatchlistRequest.SerializeToString,
                response_deserializer=watchlists__pb2.RemoveMovieFromWatchlistResponse.FromString,
                _registered_method=True)


class WatchlistServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListWatchlists(self, request, context):
        """Unary: list all watchlists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWatchlist(self, request, context):
        """Unary: get a single watchlist (with its movies)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateWatchlist(self, request, context):
        """Unary: create a watchlist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWatchlist(self, request, context):
        """Unary: update a watchlist title
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWatchlist(self, request, context):
        """Unary: delete a watchlist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserWatchlists(self, request, context):
        """Unary: list watchlists belonging to a user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMovieToWatchlist(self, request, context):
        """Unary: add a movie to a watchlist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveMovieFromWatchlist(self, request, context):
        """Unary: remove a movie from a watchlist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WatchlistServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListWatchlists': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWatchlists,
                    request_deserializer=watchlists__pb2.ListWatchlistsRequest.FromString,
                    response_serializer=watchlists__pb2.ListWatchlistsResponse.SerializeToString,
            ),
            'GetWatchlist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWatchlist,
                    request_deserializer=watchlists__pb2.GetWatchlistRequest.FromString,
                    response_serializer=watchlists__pb2.GetWatchlistResponse.SerializeToString,
            ),
            'CreateWatchlist': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWatchlist,
                    request_deserializer=watchlists__pb2.CreateWatchlistRequest.FromString,
                    response_serializer=watchlists__pb2.CreateWatchlistResponse.SerializeToString,
            ),
            'UpdateWatchlist': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWatchlist,
                    request_deserializer=watchlists__pb2.UpdateWatchlistRequest.FromString,
                    response_serializer=watchlists__pb2.UpdateWatchlistResponse.SerializeToString,
            ),
            'DeleteWatchlist': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWatchlist,
                    request_deserializer=watchlists__pb2.DeleteWatchlistRequest.FromString,
                    response_serializer=watchlists__pb2.DeleteWatchlistResponse.SerializeToString,
            ),
            'GetUserWatchlists': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserWatchlists,
                    request_deserializer=watchlists__pb2.GetUserWatchlistsRequest.FromString,
                    response_serializer=watchlists__pb2.GetUserWatchlistsResponse.SerializeToString,
            ),
            'AddMovieToWatchlist': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMovieToWatchlist,
                    request_deserializer=watchlists__pb2.AddMovieToWatchlistRequest.FromString,
                    response_serializer=watchlists__pb2.AddMovieToWatchlistResponse.SerializeToString,
            ),
            'RemoveMovieFromWatchlist': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveMovieFromWatchlist,
                    request_deserializer=watchlists__pb2.RemoveMovieFromWatchlistRequest.FromString,
                    response_serializer=watchlists__pb2.RemoveMovieFromWatchlistResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'movieplatform.watchlists.v1.WatchlistService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('movieplatform.watchlists.v1.WatchlistService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WatchlistService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListWatchlists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movieplatform.watchlists.v1.WatchlistService/ListWatchlists',
            watchlists__pb2.ListWatchlistsRequest.SerializeToString,
            watchlists__pb2.ListWatchlistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWatchlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movieplatform.watchlists.v1.WatchlistService/GetWatchlist',
            watchlists__pb2.GetWatchlistRequest.SerializeToString,
            watchlists__pb2.GetWatchlistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateWatchlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movieplatform.watchlists.v1.WatchlistService/CreateWatchlist',
            watchlists__pb2.CreateWatchlistRequest.SerializeToString,
            watchlists__pb2.CreateWatchlistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWatchlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movieplatform.watchlists.v1.WatchlistService/UpdateWatchlist',
            watchlists__pb2.UpdateWatchlistRequest.SerializeToString,
            watchlists__pb2.UpdateWatchlistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteWatchlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movieplatform.watchlists.v1.WatchlistService/DeleteWatchlist',
            watchlists__pb2.DeleteWatchlistRequest.SerializeToString,
            watchlists__pb2.DeleteWatchlistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserWatchlists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movieplatform.watchlists.v1.WatchlistService/GetUserWatchlists',
            watchlists__pb2.GetUserWatchlistsRequest.SerializeToString,
            watchlists__pb2.GetUserWatchlistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMovieToWatchlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movieplatform.watchlists.v1.WatchlistService/AddMovieToWatchlist',
            watchlists__pb2.AddMovieToWatchlistRequest.SerializeToString,
            watchlists__pb2.AddMovieToWatchlistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveMovieFromWatchlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movieplatform.watchlists.v1.WatchlistService/RemoveMovieFromWatchlist',
            watchlists__pb2.RemoveMovieFromWatchlistRequest.SerializeToString,
            watchlists__pb2.RemoveMovieFromWatchlistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
