apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: group8-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: group8-secret-store
    kind: SecretStore
  target:
    name: group8-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: group8-db-user
    - secretKey: DB_PASSWORD
      remoteRef:
        key: group8-db-password
    - secretKey: KEYCLOAK_CLIENT_SECRET
      remoteRef:
        key: group8-keycloak-client-secret
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: group8-admin-password
