apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: group8-secret-store
  namespace: default
spec:
  provider:
    gcpsm:
      projectID: PLACEHOLDER_PROJECT_ID
      auth:
        workloadIdentity:
          clusterLocation: PLACEHOLDER_CLUSTER_ZONE
          clusterName: PLACEHOLDER_CLUSTER_NAME
          clusterProjectID: PLACEHOLDER_PROJECT_ID
          serviceAccountRef:
            name: eso-sa
