FROM python:3.11-slim

WORKDIR /review-system

COPY requirements.txt .

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python -m grpc_tools.protoc \
    -I. \
    --python_out=. \
    --grpc_python_out=. \
    grpc_files/rating.proto

RUN python -m grpc_tools.protoc \
    -I. \
    --python_out=. \
    --grpc_python_out=. \
    movies/movies.proto

RUN python -m grpc_tools.protoc \
    -I. \
    --python_out=. \
    --grpc_python_out=. \
    users/users.proto

RUN sed -i 's/\r//' start.sh
RUN chmod +x start.sh

ENV REST_PORT=8003
ENV GRPC_PORT=50055

EXPOSE ${REST_PORT} ${GRPC_PORT}

CMD ["sh", "start.sh"]