# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import badges_pb2 as badges__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in badges_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BadgeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListBadges = channel.unary_unary(
                '/movieplatform.badges.v1.BadgeService/ListBadges',
                request_serializer=badges__pb2.ListBadgesRequest.SerializeToString,
                response_deserializer=badges__pb2.ListBadgesResponse.FromString,
                _registered_method=True)
        self.GetBadge = channel.unary_unary(
                '/movieplatform.badges.v1.BadgeService/GetBadge',
                request_serializer=badges__pb2.GetBadgeRequest.SerializeToString,
                response_deserializer=badges__pb2.GetBadgeResponse.FromString,
                _registered_method=True)
        self.CreateBadge = channel.unary_unary(
                '/movieplatform.badges.v1.BadgeService/CreateBadge',
                request_serializer=badges__pb2.CreateBadgeRequest.SerializeToString,
                response_deserializer=badges__pb2.CreateBadgeResponse.FromString,
                _registered_method=True)
        self.UpdateBadge = channel.unary_unary(
                '/movieplatform.badges.v1.BadgeService/UpdateBadge',
                request_serializer=badges__pb2.UpdateBadgeRequest.SerializeToString,
                response_deserializer=badges__pb2.UpdateBadgeResponse.FromString,
                _registered_method=True)
        self.DeleteBadge = channel.unary_unary(
                '/movieplatform.badges.v1.BadgeService/DeleteBadge',
                request_serializer=badges__pb2.DeleteBadgeRequest.SerializeToString,
                response_deserializer=badges__pb2.DeleteBadgeResponse.FromString,
                _registered_method=True)
        self.GetUserBadges = channel.unary_unary(
                '/movieplatform.badges.v1.BadgeService/GetUserBadges',
                request_serializer=badges__pb2.GetUserBadgesRequest.SerializeToString,
                response_deserializer=badges__pb2.GetUserBadgesResponse.FromString,
                _registered_method=True)
        self.AwardBadge = channel.unary_unary(
                '/movieplatform.badges.v1.BadgeService/AwardBadge',
                request_serializer=badges__pb2.AwardBadgeRequest.SerializeToString,
                response_deserializer=badges__pb2.AwardBadgeResponse.FromString,
                _registered_method=True)
        self.StreamUserBadgeEvents = channel.unary_stream(
                '/movieplatform.badges.v1.BadgeService/StreamUserBadgeEvents',
                request_serializer=badges__pb2.StreamUserBadgeEventsRequest.SerializeToString,
                response_deserializer=badges__pb2.BadgeAwardedEvent.FromString,
                _registered_method=True)


class BadgeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListBadges(self, request, context):
        """Unary: list all badge definitions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBadge(self, request, context):
        """Unary: get a single badge definition
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBadge(self, request, context):
        """Unary: create a badge definition
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBadge(self, request, context):
        """Unary: update a badge definition
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBadge(self, request, context):
        """Unary: delete a badge definition
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserBadges(self, request, context):
        """Unary: list badges awarded to a user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AwardBadge(self, request, context):
        """Unary: award a badge to a user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamUserBadgeEvents(self, request, context):
        """Server streaming: push a BadgeAwardedEvent each time the user earns a badge
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BadgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListBadges': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBadges,
                    request_deserializer=badges__pb2.ListBadgesRequest.FromString,
                    response_serializer=badges__pb2.ListBadgesResponse.SerializeToString,
            ),
            'GetBadge': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBadge,
                    request_deserializer=badges__pb2.GetBadgeRequest.FromString,
                    response_serializer=badges__pb2.GetBadgeResponse.SerializeToString,
            ),
            'CreateBadge': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBadge,
                    request_deserializer=badges__pb2.CreateBadgeRequest.FromString,
                    response_serializer=badges__pb2.CreateBadgeResponse.SerializeToString,
            ),
            'UpdateBadge': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBadge,
                    request_deserializer=badges__pb2.UpdateBadgeRequest.FromString,
                    response_serializer=badges__pb2.UpdateBadgeResponse.SerializeToString,
            ),
            'DeleteBadge': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBadge,
                    request_deserializer=badges__pb2.DeleteBadgeRequest.FromString,
                    response_serializer=badges__pb2.DeleteBadgeResponse.SerializeToString,
            ),
            'GetUserBadges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserBadges,
                    request_deserializer=badges__pb2.GetUserBadgesRequest.FromString,
                    response_serializer=badges__pb2.GetUserBadgesResponse.SerializeToString,
            ),
            'AwardBadge': grpc.unary_unary_rpc_method_handler(
                    servicer.AwardBadge,
                    request_deserializer=badges__pb2.AwardBadgeRequest.FromString,
                    response_serializer=badges__pb2.AwardBadgeResponse.SerializeToString,
            ),
            'StreamUserBadgeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamUserBadgeEvents,
                    request_deserializer=badges__pb2.StreamUserBadgeEventsRequest.FromString,
                    response_serializer=badges__pb2.BadgeAwardedEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'movieplatform.badges.v1.BadgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('movieplatform.badges.v1.BadgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BadgeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListBadges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movieplatform.badges.v1.BadgeService/ListBadges',
            badges__pb2.ListBadgesRequest.SerializeToString,
            badges__pb2.ListBadgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBadge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movieplatform.badges.v1.BadgeService/GetBadge',
            badges__pb2.GetBadgeRequest.SerializeToString,
            badges__pb2.GetBadgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBadge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movieplatform.badges.v1.BadgeService/CreateBadge',
            badges__pb2.CreateBadgeRequest.SerializeToString,
            badges__pb2.CreateBadgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBadge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movieplatform.badges.v1.BadgeService/UpdateBadge',
            badges__pb2.UpdateBadgeRequest.SerializeToString,
            badges__pb2.UpdateBadgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBadge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movieplatform.badges.v1.BadgeService/DeleteBadge',
            badges__pb2.DeleteBadgeRequest.SerializeToString,
            badges__pb2.DeleteBadgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserBadges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movieplatform.badges.v1.BadgeService/GetUserBadges',
            badges__pb2.GetUserBadgesRequest.SerializeToString,
            badges__pb2.GetUserBadgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AwardBadge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movieplatform.badges.v1.BadgeService/AwardBadge',
            badges__pb2.AwardBadgeRequest.SerializeToString,
            badges__pb2.AwardBadgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamUserBadgeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/movieplatform.badges.v1.BadgeService/StreamUserBadgeEvents',
            badges__pb2.StreamUserBadgeEventsRequest.SerializeToString,
            badges__pb2.BadgeAwardedEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
