FROM python:3.11-slim

WORKDIR /subscriptions

ENV PYTHONUNBUFFERED=1

COPY requirements.txt requirements.txt

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python -m grpc_tools.protoc \
    -I. \
    --python_out=. \
    --grpc_python_out=. \
    grpc_files/subscriptions.proto

RUN python -m grpc_tools.protoc \
    -I. \
    --python_out=. \
    --grpc_python_out=. \
    users/users.proto

RUN sed -i 's/\r//' start.sh
RUN chmod +x start.sh

ENV REST_PORT=8005
ENV GRPC_PORT=50057

EXPOSE ${REST_PORT} ${GRPC_PORT}

CMD ["/bin/sh", "/subscriptions/start.sh"]
