# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x04user\"U\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0e\n\x06gender\x18\x04 \x01(\t\x12\x0b\n\x03\x61ge\x18\x05 \x01(\x05\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"+\n\x0fGetUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"&\n\x13ValidateUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"&\n\x14ValidateUserResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32\x8c\x01\n\x0bUserService\x12\x36\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12\x45\n\x0cValidateUser\x12\x19.user.ValidateUserRequest\x1a\x1a.user.ValidateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=21
  _globals['_USER']._serialized_end=106
  _globals['_GETUSERREQUEST']._serialized_start=108
  _globals['_GETUSERREQUEST']._serialized_end=141
  _globals['_GETUSERRESPONSE']._serialized_start=143
  _globals['_GETUSERRESPONSE']._serialized_end=186
  _globals['_VALIDATEUSERREQUEST']._serialized_start=188
  _globals['_VALIDATEUSERREQUEST']._serialized_end=226
  _globals['_VALIDATEUSERRESPONSE']._serialized_start=228
  _globals['_VALIDATEUSERRESPONSE']._serialized_end=266
  _globals['_USERSERVICE']._serialized_start=269
  _globals['_USERSERVICE']._serialized_end=409
# @@protoc_insertion_point(module_scope)
