name: teste

on:
  push:
    branches: [tpereira]
  pull_request:
    branches: [tpereira]

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show repo context
        run: |
          echo "${{ github.repository }}"
          echo "${{ github.repository_owner }}"